// GENERATED by Paradise.Godot.Editor; overwritten on package updates.
// Keep this path and Godot-generated .uid committed: scenes store both, and moving them
// detaches nodes and loses component values.
//
// Delegate to the plain AuthoredEntityCore: cross-assembly GodotObject inheritance causes
// duplicate script registrations on reload (godotengine/godot#75352).
#if TOOLS
using System;
using Godot;
using ParadiseGodot.Authoring;

namespace ParadiseGodot.Authoring
{
    [Tool]
    [GlobalClass]
    public partial class AuthoredEntityNode : Node3D, IAuthoredEntity
    {
        // Initialize lazily: _Notification runs before field initializers.
        private AuthoredEntityCore? _core;
        private AuthoredEntityCore Core => _core ??= new AuthoredEntityCore(this);

        public Node3D Node => this;

        public string ModelPath
        {
            get => Core.ModelPath;
            set => Core.ModelPath = value;
        }

        public Guid EntityGuid => Core.EntityGuid;

        public void AdoptDocumentComponents(
            System.Collections.Generic.IReadOnlyList<Paradise.Assets.Documents.PrefabComponent> components) =>
            Core.AdoptDocumentComponents(components);

        public ParadiseGodot.Documents.AuthoredEdits Edits => Core.Edits;

        public System.Collections.Generic.IReadOnlyDictionary<string, ParadiseGodot.Documents.AuthoredValue>
            AuthoredValues() => Core.AuthoredValues();

        public bool RestoreEntityGuid(Guid value) => Core.RestoreEntityGuid(value);

        public Guid EnsureEntityGuid() => Core.EnsureEntityGuid();

        public System.Collections.Generic.IReadOnlyDictionary<string, ParadiseGodot.Documents.AuthoredValue>
            BakedHostValues(ParadiseGodot.Project.AssetReferenceResolver? assets = null) =>
            Core.BakedHostValues(assets);

        // These Godot hooks provide inspector properties and persistence. Only a running Godot
        // can verify them; deleting them silently breaks the node while unit tests still pass.
        public override Godot.Collections.Array<Godot.Collections.Dictionary> _GetPropertyList() =>
            Core.BuildPropertyList();

        public override Variant _Get(StringName property) => Core.GetAuthored(property);

        public override bool _Set(StringName property, Variant value) =>
            Core.SetAuthored(property, value);

        public override void _Notification(int what) => Core.OnNotification(what);

        public override void _Ready() => Core.OnReady();
    }
}
#endif
