// GENERATED by the Paradise.Godot.Editor package. Committed on purpose, and its path is load-
// bearing: scenes serialize a script attachment as res:// path + uid, so moving or deleting this
// file detaches every node that uses it and silently drops the component values riding on
// _Set/_GetPropertyList. Edits are overwritten on the next package version bump; change
// AuthoredEntityNodeBase instead.
//
// Its .uid is NOT generated - Godot mints that on first import and it is committed alongside.
#if TOOLS
using Godot;

namespace ParadiseGodot.Authoring
{
    /// <summary>THE entity node. Implementation is in the package; see AuthoredEntityNodeBase.</summary>
    [Tool]
    [GlobalClass]
    public partial class AuthoredEntityNode : AuthoredEntityNodeBase { }
}
#endif
