// GENERATED by the Paradise.Godot.Editor package. Committed on purpose - Godot resolves
// plugin.cfg's script= as a res:// path, so this file has to exist in the repo. Edits are
// overwritten on the next package version bump; change ParadiseExportPluginBase instead.
#if TOOLS
using Godot;

namespace ParadiseGodot
{
    /// <summary>res:// entry point for the addon. The implementation is in the package.</summary>
    [Tool]
    public partial class ParadiseExportPlugin : ParadiseExportPluginBase { }
}
#endif
