// GENERATED by Paradise.Godot.Editor; overwritten on package updates. Change ExportPluginCore.
// Keep committed: plugin.cfg loads this res:// path.
//
// Delegation avoids duplicate script registrations from cross-assembly GodotObject inheritance
// on reload (godotengine/godot#75352). Named forwarders let callables resolve the current assembly;
// Callable.From delegates retain GC handles that become invalid on reload.
#if TOOLS
using Godot;

namespace ParadiseGodot
{
    [Tool]
    public partial class ParadiseExportPlugin : EditorPlugin
    {
        private ExportPluginCore? _core;
        private ExportPluginCore Core => _core ??= new ExportPluginCore(this);

        public override void _EnterTree() => Core.EnterTree();

        public override void _ExitTree() => Core.ExitTree();

        public void OnOpenDocument() => Core.OnOpenDocument();

        public void OnDocumentChosen(string path) => Core.OnDocumentChosen(path);

        public void OnDocumentDialogClosed() => Core.OnDocumentDialogClosed();


        public void OnProjectSetup() => ProjectSetup.Run();

        public void OnOpenSettings() => Core.OnOpenSettings();

        public void OnPlayDotnet() => Core.OnPlayDotnet();

        public void OnStopDotnet() => Core.OnStopDotnet();

        public void OnExtractModels() => Core.OnExtractModels();

        public void OnToggleWatch() => Core.OnToggleWatch();

        public void OnConvertProject() => Core.OnConvertProject();
    }
}
#endif
