// GENERATED by the Paradise.Godot.Editor package. Committed on purpose - Godot resolves
// plugin.cfg's script= as a res:// path, so this file has to exist in the repo. Edits are
// overwritten on the next package version bump; change ExportPluginCore instead.
//
// It DELEGATES rather than inherits: a res:// script may not derive from a GodotObject-derived
// type declared in another assembly, because Godot registers the base as a script type too and
// its ScriptTypeBiMap then throws a duplicate-key exception on every assembly reload, breaking
// editor hot-reload. See godotengine/godot#75352.
//
// The forwarders below are the addon's menu items and toolbar button. They exist as NAMED methods
// on this GodotObject so the core can wire its UI with name-based callables, which re-resolve
// against the current assembly on every invocation. A Callable.From(delegate) instead holds a GC
// handle that dies with the assembly on reload, after which every click fails with
// "Parameter delegate_handle.value is null ... ManagedCallableMiddleman:: Method not found".
#if TOOLS
using Godot;

namespace ParadiseGodot
{
    /// <summary>res:// entry point for the addon. The implementation is in the package.</summary>
    [Tool]
    public partial class ParadiseExportPlugin : EditorPlugin
    {
        private ExportPluginCore? _core;
        private ExportPluginCore Core => _core ??= new ExportPluginCore(this);

        public override void _EnterTree() => Core.EnterTree();

        public override void _ExitTree() => Core.ExitTree();

        public void OnGenerateModelPrefabs() => Core.OnGenerateModelPrefabs();

        public void OnGeneratePrimitives() => Core.OnGeneratePrimitives();

        public void OnConvertModels() => Core.OnConvertModels();

        public void OnConvertDataGlbs() => Core.OnConvertDataGlbs();

        public void OnProjectSetup() => ProjectSetup.Run();

        public void OnOpenSettings() => Core.OnOpenSettings();

        public void OnPlayDotnet() => Core.OnPlayDotnet();
    }
}
#endif
