#if TOOLS
using System.IO;
using Godot;

namespace ParadiseGodot.Pipeline
{
    /// <summary>
    /// Generates the shared unit-primitive GLBs used by scene entities that have no authored art
    /// (ground/obstacle/crate → cube, ball → sphere, agent → capsule). Written once to
    /// <c>res://data/primitives/</c>; entities reference them via <c>EntityExport.ModelPath</c>
    /// and express their real size through the entity transform SCALE (a unit collider folds to
    /// match). Most primitives are untextured — per-entity look comes from material-slot overrides.
    /// The exception is <c>sphere_ball</c>, which carries a baked gradient image (balls need a
    /// texture); the externalize/KTX2 pass turns it into a sidecar .ktx2 like any other GLB.
    ///
    /// Uses Godot's native <see cref="GltfDocument"/> (same approach the old MeshGlbExporter used),
    /// so the GLBs carry correct normals/UVs generated by Godot's primitive meshes.
    /// </summary>
    internal static class PrimitiveGlbGenerator
    {
        private static string OutputDir => ParadisePaths.PrimitivesDir;

        public static void GenerateAll()
        {
            // Cube/sphere are unit-sized (scaled per entity). The capsule is authored at the
            // agent's REAL dimensions (r0.4, h1.8): a capsule's hemispherical caps cannot be
            // reproduced by non-uniform TRS scale of a unit capsule, and only the agent uses one,
            // so it renders at scale 1.
            Generate("cube", new BoxMesh { Size = new Vector3(1f, 1f, 1f) });
            Generate("sphere", new SphereMesh { Radius = 0.5f, Height = 1.0f });
            Generate("capsule", new CapsuleMesh { Radius = 0.4f, Height = 1.8f });
            // Balls need a texture (the old procedural GradientTexture2D). A shared textured
            // sphere carries a CONCRETE gradient image (embeds headless — procedural textures do
            // NOT rasterize without a GPU); each ball tints it via its own material-slot override.
            Generate("sphere_ball", new SphereMesh { Radius = 0.5f, Height = 1.0f, Material = BuildBallGradientMaterial() });
            EditorInterface.Singleton.GetResourceFilesystem().Scan();
            GD.Print($"[Paradise.Export] Generated primitive GLBs in {OutputDir}/.");
        }

        // The ball gradient: 8 alternating white/dark vertical bands (constant interpolation),
        // reproducing the removed `tex_ball` GradientTexture2D. Base color is white so the
        // per-ball albedo_color override multiplies through as the visible tint.
        private static StandardMaterial3D BuildBallGradientMaterial()
        {
            const int size = 256;
            const int bands = 8;
            var image = Image.CreateEmpty(size, size, false, Image.Format.Rgb8);
            var white = new Color(1f, 1f, 1f);
            var dark = new Color(0.2f, 0.2f, 0.2f);
            for (int band = 0; band < bands; band++)
            {
                image.FillRect(new Rect2I(band * size / bands, 0, size / bands, size), band % 2 == 0 ? white : dark);
            }

            return new StandardMaterial3D
            {
                AlbedoColor = white,
                AlbedoTexture = ImageTexture.CreateFromImage(image),
            };
        }

        private static void Generate(string name, Mesh mesh)
        {
            var root = new Node3D { Name = name };
            var meshInstance = new MeshInstance3D { Name = "Mesh", Mesh = mesh };
            root.AddChild(meshInstance);
            // AppendFromScene exports only OWNED descendants (same rule as PackedScene.Pack).
            meshInstance.Owner = root;
            try
            {
                var document = new GltfDocument();
                var state = new GltfState();
                Error error = document.AppendFromScene(root, state);
                if (error != Error.Ok)
                {
                    throw new IOException($"GltfDocument.AppendFromScene failed for primitive '{name}': {error}.");
                }

                byte[] bytes = document.GenerateBuffer(state);
                if (bytes is null || bytes.Length == 0)
                {
                    throw new IOException($"GltfDocument.GenerateBuffer produced no data for primitive '{name}'.");
                }

                string outputPath = ProjectSettings.GlobalizePath($"{OutputDir}/{name}.glb");
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
                File.WriteAllBytes(outputPath, bytes);
                GD.Print($"[Paradise.Export] Wrote {OutputDir}/{name}.glb");
            }
            finally
            {
                root.Free();
            }
        }
    }
}
#endif
