// GENERATED by the Paradise.Godot.Editor package. Committed on purpose, and its path is load-
// bearing: scenes serialize a script attachment as res:// path + uid, so moving or deleting this
// file detaches every node that uses it and silently drops the component values riding on
// _Set/_GetPropertyList. Edits are overwritten on the next package version bump.
//
// Its .uid is NOT generated - Godot mints that on first import and it is committed alongside.
//
// It DELEGATES rather than inherits, and that is the whole point. A res:// script may not derive
// from a GodotObject-derived type declared in another assembly: Godot registers the base as a
// script type too, and its ScriptTypeBiMap then throws a duplicate-key exception on every
// assembly reload, which breaks editor hot-reload and pins the inspector to "This inspector might
// be out of date". See godotengine/godot#75352. AuthoredEntityCore is a plain class, so Godot
// never looks at it, and all the behaviour still lives in the package.
#if TOOLS
using System;
using System.Collections.Generic;
using Godot;
using Paradise.Export.Data;
using ParadiseGodot.Authoring;

namespace ParadiseGodot.Authoring
{
    /// <summary>THE entity node. Implementation is in the package; see AuthoredEntityCore.</summary>
    [Tool]
    [GlobalClass]
    public partial class AuthoredEntityNode : Node3D, IAuthoredEntity
    {
        // Lazy, not a field initializer: _Notification fires during construction, before an
        // initializer would have run.
        private AuthoredEntityCore? _core;
        private AuthoredEntityCore Core => _core ??= new AuthoredEntityCore(this);

        public Node3D Node => this;

        public string ModelPath
        {
            get => Core.ModelPath;
            set => Core.ModelPath = value;
        }

        public string ResolvedKind => Core.ResolvedKind;

        public Guid EnsureEntityGuid() => Core.EnsureEntityGuid();

        public IEnumerable<AuthoredComponentData> ExportAuthoredComponents() =>
            Core.ExportAuthoredComponents();

        public override Godot.Collections.Array<Godot.Collections.Dictionary> _GetPropertyList() =>
            Core.BuildPropertyList();

        public override Variant _Get(StringName property) => Core.GetAuthored(property);

        public override bool _Set(StringName property, Variant value) =>
            Core.SetAuthored(property, value);

        public override void _Notification(int what) => Core.OnNotification(what);

        public override void _Ready() => Core.OnReady();
    }
}
#endif
